// src/app/obs/[slug]/page.tsx
"use client";
import { cn } from "~/@/lib/utils";
import { AnimatedList } from "~/@/components/animated-list";
import { api } from "~/trpc/react";
import { use } from "react";
import { Loader2Icon } from "lucide-react";

function butterParse(a: string): number {
  if (a === "NM" || Number.isNaN(a)) {
    return 0;
  } else if (a === null) {
    return 0;
  } else if (a === "DNS" || a === "DQ" || a === "DNF" || a === "DSQ") {
    return 0;
  } else {
    return parseFloat(a);
  }
}

export default function Obs({ params }: { params: Promise<{ slug: string }> }) {
  const cachedParams = use(params ?? { slug: "" }) as { slug: string };
  const compId = cachedParams.slug?.replace("-", "/");
  const competitionDetailsId = cachedParams.slug?.split("-")[0];
  const obsAthletes = api.competition.getAthletes.useQuery(
    { compId },
    { refetchInterval: 1000 },
  );
  const obsCompetition = api.competition.getCompetitionDetails.useQuery({
    competitionDetailsId: competitionDetailsId!,
  });

  if (obsAthletes.isLoading || obsCompetition.isLoading) {
    return <Loader2Icon className="animate-spin" />;
  }

  if (obsAthletes.isError || obsCompetition.isError) {
    return <div className="text-red-500">Failed to load competition data</div>;
  }

  if (!obsAthletes.data || !obsCompetition.data) {
    return <div>No data available</div>;
  }

  return (
    <div className="-mx-2 max-w-xs text-gray-50">
      <div className="w-full max-w-xs border-t-2 border-cyan-300 bg-black/90">
        <h2 className="px-2 text-cyan-300 uppercase">
          {obsAthletes.data?.Rounds[0]?.Name}
        </h2>
        <div className="flex justify-between">
          <h3 className="bg-cyan-300 px-2 text-black uppercase">
            {obsAthletes.data?.Name}
          </h3>
          <h4 className="px-2 uppercase">Tulos</h4>
        </div>
        <AnimatedList>
          {obsAthletes.data?.Rounds.map((round) =>
            round.TotalResults.sort((a, b) => {
              const resultA = butterParse(a.Result);
              const resultB = butterParse(b.Result);
              console.log(
                `${a.Name} ResultA: ${resultA} unformatted: ${a.Result}`,
              );
              console.log(
                `${b.Name} ResultB: ${resultB} unformatted: ${b.Result}`,
              );
              if (resultA === null || resultB === null) {
                return -1;
              } else if (resultA === -1) {
                return 1;
              } else if (resultB === -1) {
                return -1;
              } else if (resultA === 0) {
                return 1;
              } else if (resultB === 0) {
                return -1;
              } else {
                return resultA > resultB ? -1 : 1;
              }
            }).map((a) => (
              <li
                key={a.Id}
                className="flex flex-wrap justify-between border-t-2 border-black/50"
              >
                <div className="flex flex-[1_1_100%] justify-between px-4 py-1">
                  {a.Name}
                  <span>{a.Result}</span>
                </div>
                {a.Attempts.length > 1 && (
                  <ul
                    className={cn(
                      "ml-1 flex-[1_1_100%] bg-gray-300 text-black",
                      a.Id ? "flex" : "hidden",
                    )}
                  >
                    {a.Attempts === null ? (
                      <p className="opacity-0">no</p>
                    ) : (
                      a.Attempts?.map((at, idx) => (
                        <li
                          key={idx}
                          className={cn(
                            a.Result === at.Line1 && "bg-cyan-300/50!",
                            "flex min-w-[16.7%] flex-col px-1 py-2 even:bg-gray-200",
                          )}
                        >
                          <span>{at.Line1}</span>
                          {at.Line2 && <span>{at.Line2}</span>}
                        </li>
                      ))
                    )}
                  </ul>
                )}
              </li>
            )),
          )}
        </AnimatedList>
      </div>
      <h1 className="mt-1 inline-flex bg-black/90 p-1 text-cyan-300 uppercase">
        {obsCompetition.data?.Competition.Name}
      </h1>
    </div>
  );
}

// src/routes/obs/[slug]/+page.svelte
<script lang="ts">
	import { page } from "$app/stores";
	import { api } from "$lib/api";
	import { sortByResult } from "$lib/results";
	import { cn } from "$lib/utils";
	import type { Competition, CompetitionProperties } from "~/types/comp";

	const slug = $derived($page.params.slug ?? "");
	const compId = $derived(slug.split("-", 2)[0] ?? "");
	const eventId = $derived(slug.split("-", 2)[1] ?? "");
	const selectedHeat = $derived($page.url.searchParams.get("heat"));
	const selectedRound = $derived($page.url.searchParams.get("round"));

	let competition = $state<Competition | null>(null);
	let compDetails = $state<CompetitionProperties | null>(null);
	let isLoading = $state(true);
	let isError = $state(false);

	async function fetchData() {
		if (!compId || !eventId) return;
		isLoading = true;
		isError = false;
		try {
			const [comp, details] = await Promise.all([
				api.getAthletes(`${compId}/${eventId}`),
				api.getCompetitionDetails(compId),
			]);
			competition = comp;
			compDetails = details;
			isLoading = false;
		} catch {
			isError = true;
			isLoading = false;
		}
	}

	$effect(() => {
		fetchData();
	});

	$effect(() => {
		if (!competition || !eventId) return;

		const interval = setInterval(async () => {
			try {
				const comp = await api.getAthletes(`${compId}/${eventId}`);
				competition = comp;
			} catch {
				// keep old data
			}
		}, 30000);

		return () => clearInterval(interval);
	});

	const eventCategory = $derived("Field");
	const isTrack = $derived(eventCategory === "Track" || eventCategory === "Relay");

	const roundIndex = $derived((Number(selectedRound) || 1) - 1);
	const rounds = $derived(competition?.Rounds?.[roundIndex]);
	const heats = $derived(rounds?.Heats ?? []);

	const heatIndexRaw = $derived(selectedHeat ? Number(selectedHeat) - 1 : null);
	const heatIndex = $derived(
		heatIndexRaw != null && Number.isInteger(heatIndexRaw) ? heatIndexRaw : null,
	);
	const heatExists = $derived(
		heatIndex != null && heatIndex >= 0 && heatIndex < heats.length,
	);
	const heat = $derived(heatExists ? heats[heatIndex] : null);

	const allocations = $derived(
		(selectedHeat ? (heat?.Allocations ?? []) : (rounds?.TotalResults ?? []))
			.slice()
			.sort((a: any, b: any) => sortByResult(a, b, "Field")),
	);

	const MAX_ATTEMPTS = 6;

	function normalizeAttempts(attempts: any[] | null | undefined): any[] {
		if (!attempts || attempts.length <= MAX_ATTEMPTS) return attempts ?? [];
		return attempts.slice(-MAX_ATTEMPTS);
	}
</script>

{#if rounds && selectedHeat && !heatExists}
	<div class="flex min-h-screen items-center justify-center">
		<div class="max-w-md rounded-lg bg-black/90 p-6 text-center">
			<p class="text-cyan-300 text-xl">Erä {selectedHeat} ei ole olemassa</p>
			<p class="mt-2 text-gray-400 text-sm">Tämä tapahtuma sisältää {heats.length} erää.</p>
		</div>
	</div>
{:else}
	<div class="max-w-xs text-gray-50">
		<div class="w-full max-w-xs border-cyan-300 border-t-2 bg-black/90">
			<h2 class="px-2 text-cyan-300 uppercase">
					{#if rounds?.Name}
						{rounds.Name}
					{:else}
						<div class="my-1 h-4 w-28 animate-pulse rounded bg-gray-700/60"></div>
					{/if}
				</h2>
			<div class="flex justify-between">
				<h3 class="bg-cyan-300 px-2 text-black uppercase">
					{#if competition?.Name}
						{competition.Name}
					{:else}
						<div class="my-1 h-4 w-24 animate-pulse rounded bg-black/20"></div>
					{/if}
				</h3>
				<h4 class="px-2 uppercase">Tulos</h4>
			</div>

			{#if isError}
				<p class="px-2 py-1 text-cyan-600 text-xl">Failed to load</p>
			{:else if isLoading}
				<ul>
					{#each Array(8) as _, i}
						<li class="border-black/50 border-t-2" key={i}>
							<div class="flex flex-[1_1_100%] justify-between px-4 py-2">
								<div class="h-4 w-40 animate-pulse rounded bg-gray-700/60"></div>
								<div class="h-4 w-16 animate-pulse rounded bg-gray-700/60"></div>
							</div>
						</li>
					{/each}
				</ul>
			{:else if !isLoading && !isError && !rounds}
				<p class="px-2 py-1 text-cyan-600 text-xl">Kierros ei saatavilla</p>
			{:else}
				<ul class="flex flex-col gap-1">
					{#each allocations as a (a.Id)}
						<li class="flex flex-wrap justify-between border-black/50 border-t-2">
							<div class="flex flex-[1_1_100%] justify-between px-4 py-1">
								{a.Name}
								<span class="tabular-nums">{a.Result}</span>
							</div>
							{#if !isTrack}
								<ul class="ml-1 flex flex-[1_1_100%] bg-gray-300 text-black">
									{#if a.Attempts === null}
										<li aria-hidden="true" class="invisible">no</li>
									{:else}
										{#each normalizeAttempts(a.Attempts) as at, i}
											<li
												class={cn(
													"flex min-w-[16.7%] flex-col items-center justify-center px-1 py-2 even:bg-gray-200",
													a.Result === at.Line1 && "bg-cyan-300/50!",
												)}
											>
												<span>{at.Line1}</span>
												{#if at.Line2}<span>{at.Line2}</span>{/if}
											</li>
										{/each}
									{/if}
								</ul>
							{/if}
						</li>
					{/each}
				</ul>
			{/if}
		</div>
		<h1 class="mt-1 inline-flex bg-black/90 p-1 text-cyan-300 uppercase">
			{#if compDetails?.Competition.Name}
				{compDetails.Competition.Name}
			{:else}
				<div class="my-1 h-4 w-24 animate-pulse rounded bg-gray-700/60"></div>
			{/if}
		</h1>
	</div>
{/if}
