// src/app/competition/[slug]/page.tsx
import { ClipboardList, InfoIcon, Trophy, Users } from "lucide-react";
import {
	CompetitionLayout,
	ParticipantLayout,
	ResultLayout,
} from "~/@/components/competition-layout";
import { Embed } from "~/@/components/embed";
import { EventSwitcher } from "~/@/components/event-switcher";
import { Navbar } from "~/@/components/navbar";
import { RoundProvider } from "~/@/components/round-provider";
import { Button } from "~/@/components/ui/button";
import {
	Popover,
	PopoverContent,
	PopoverTrigger,
} from "~/@/components/ui/popover";
import { Separator } from "~/@/components/ui/separator";
import {
	Tabs,
	TabsContent,
	TabsList,
	TabsTrigger,
} from "~/@/components/ui/tabs";
import { api } from "~/trpc/server";

// TODO: make the popover link not be hardcoded
function ObsPopover({ slug }: { slug: string }) {
	return (
		<Popover>
			<PopoverTrigger className="top-9 right-5 z-50">
				<Button className="px-2" size="icon" variant="ghost">
					<InfoIcon />
				</Button>
			</PopoverTrigger>
			<PopoverContent className="w-96">
				<div className="flex flex-col gap-4">
					<div className="space-y-2">
						<h4 className="font-medium leading-none">OBS Overlay</h4>
						<p className="text-muted-foreground text-sm">
							jos haluut näyttää vain tietyn erän tulokset niin tee näin
						</p>
						<Separator className="" />
						<div className="break-all rounded-lg border bg-popover-foreground/10 p-3 pr-12 font-mono text-gray-300 text-sm">
							https://livetila.vercel.app/obs/{slug}
							<span className="rounded bg-cyan-300/40 px-1 py-0.5 text-white">
								?heat=1
							</span>
						</div>
					</div>
					<div className="flex gap-4">
						<Embed slug={slug} />
					</div>
				</div>
			</PopoverContent>
		</Popover>
	);
}

export default async function Comp({
	params,
}: {
	params: Promise<{ slug: string }>;
}) {
	const { slug } = await params;
	console.log("Comp params:", slug);
	const compId = slug?.slice(0, slug.indexOf("-"));
	console.log("Comp id:", compId);
	const eventId = slug?.slice(slug.indexOf("-") + 1);
	console.log("Event id:", eventId);
	const compSTD = await api.competition.getCompetitionDetails({
		competitionDetailsId: compId,
	});
	const athletes = await api.competition.getAthletes({
		compId: `${compId}/${eventId}`,
	});
	const compD = await api.competition.getEvents({ compId: Number(compId) });
	// console.log("Comp data:", compD);

	return (
		<RoundProvider rounds={athletes.Rounds}>
			<Navbar />
			<main className="container relative mx-auto flex grow flex-col p-4 sm:p-8">
				<div className="flex items-center justify-between gap-2">
					<div className="flex flex-col items-start gap-2">
						<h2 className="scroll-m-20 border-b pb-2 font-semibold text-3xl tracking-tight first:mt-0">
							{compSTD.Competition.Name}
						</h2>
						<EventSwitcher
							competitionId={compId}
							currentEventId={eventId}
							events={compD}
						/>
					</div>
					<ObsPopover slug={slug} />
				</div>
				<Tabs className="mt-2 w-full" defaultValue="participants">
					<TabsList className="mb-2 grid h-auto w-full grid-cols-3 bg-transparent p-0">
						<TabsTrigger
							className="rounded-none border-transparent border-b-2 py-3 text-muted-foreground hover:border-primary/70 hover:text-foreground/70 data-[state=active]:border-primary data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-none"
							value="participants"
						>
							<div className="flex items-center justify-center gap-2">
								<span className="flex h-5 w-5 items-center justify-center rounded-full border">
									<Users className="h-3 w-3" />
								</span>
								<span className="hidden sm:block">Ilmoittautuneet</span>
							</div>
						</TabsTrigger>
						<TabsTrigger
							className="rounded-none border-transparent border-b-2 py-3 text-muted-foreground hover:border-primary/70 hover:text-foreground/70 data-[state=active]:border-primary data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-none"
							value="protocol"
						>
							<div className="flex items-center justify-center gap-2">
								<span className="flex h-5 w-5 items-center justify-center rounded-full border">
									<ClipboardList className="h-3 w-3" />
								</span>
								<span className="hidden sm:block">Pöytäkirjat</span>
							</div>
						</TabsTrigger>
						<TabsTrigger
							className="rounded-none border-transparent border-b-2 py-3 text-muted-foreground hover:border-primary/70 hover:text-foreground/70 data-[state=active]:border-primary data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-none"
							value="results"
						>
							<div className="flex items-center justify-center gap-2">
								<span className="flex h-5 w-5 items-center justify-center rounded-full border">
									<Trophy className="h-3 w-3" />
								</span>
								<span className="hidden sm:block">Tulokset</span>
							</div>
						</TabsTrigger>
					</TabsList>
					<TabsContent
						className="fade-in-50 animate-in duration-300"
						value="participants"
					>
						<ParticipantLayout athletes={athletes} />
					</TabsContent>
					<TabsContent
						className="fade-in-50 animate-in duration-300"
						value="protocol"
					>
						<CompetitionLayout />
					</TabsContent>
					<TabsContent
						className="fade-in-50 animate-in space-y-5 duration-300"
						value="results"
					>
						<ResultLayout athletes={athletes} />
					</TabsContent>
				</Tabs>
			</main>
		</RoundProvider>
	);
}

// src/routes/(app)/competition/[slug]/+page.svelte
<script lang="ts">
  import { page } from "$app/state";
  import { ClipboardList, Trophy, Users } from "@lucide/svelte";
  import ObsPopover from "$lib/components/obs-popover.svelte";
  import EventSwitcher from "$lib/components/event-switcher.svelte";
  import RoundSwitcher from "$lib/components/round-switcher.svelte";
  import TabsWithHaptics from "$lib/components/tabs-haptics.svelte";
  import RoundProvider from "$lib/components/round-provider.svelte";
  import ResultProvider from "$lib/components/result-provider.svelte";
  import ParticipantLayout from "$lib/components/participant-layout.svelte";
  import ProtocolLayout from "$lib/components/protocol-layout.svelte";
  import ResultLayout from "$lib/components/result-layout.svelte";
  import { flattenEvents } from "$lib/events";
  import { api } from "$lib/api";
  import { createQuery } from "@tanstack/svelte-query";
  import type {
    Competition,
    CompetitionProperties,
    Events,
  } from "~/types/comp";

  const slug = $derived(page.params.slug ?? "");
  const compId = $derived(slug.split("-", 2)[0] ?? "");
  const eventId = $derived(slug.split("-", 2)[1] ?? "");

  const eventsQuery = createQuery<Events>(() => ({
    queryKey: ["events", compId],
    queryFn: () => api.getEvents(compId),
    enabled: Boolean(compId),
  }));

  const compEventsRaw = $derived(eventsQuery.data ?? null);
  const compEvents = $derived(
    compEventsRaw ? flattenEvents(compEventsRaw) : [],
  );
  const selectedEvent = $derived(
    compEvents.find((e) => e.EventId === Number(eventId)),
  );
  const isTrack = $derived(selectedEvent?.Category === "Track");
  const isProgress = $derived(selectedEvent?.Status === "Progress");

  const athletesQuery = createQuery<Competition>(() => ({
    queryKey: ["athletes", compId, eventId],
    queryFn: () => api.getAthletes(`${compId}/${eventId}`),
    enabled: Boolean(compId && eventId),
    refetchInterval: isProgress ? 1000 : false,
    refetchIntervalInBackground: false,
  }));

  const detailsQuery = createQuery<CompetitionProperties>(() => ({
    queryKey: ["competition-details", compId],
    queryFn: () => api.getCompetitionDetails(compId),
    enabled: Boolean(compId),
  }));

  const competition = $derived(athletesQuery.data ?? null);
  const compDetails = $derived(detailsQuery.data ?? null);
  const isLoading = $derived(
    athletesQuery.isPending || detailsQuery.isPending || eventsQuery.isPending,
  );
  const error = $derived(
    athletesQuery.isError ? "Failed to load competition data" : null,
  );
</script>

<svelte:head>
  <title>{compDetails?.Competition.Name ?? "Kilpailu"} - Livetila</title>
</svelte:head>

<main class="container relative mx-auto flex grow flex-col px-4 py-4 sm:p-8">
  {#if !compId || !eventId}
    <div class="flex flex-col items-center justify-center py-20">
      <h2 class="font-bold text-2xl">Virheellinen linkki</h2>
      <a href="/" class="mt-4 text-primary underline">Palaa etusivulle</a>
    </div>
  {:else if isLoading}
    <div class="flex flex-col gap-4">
      <div class="flex items-center justify-between">
        <div class="h-8 w-28 animate-pulse rounded-md bg-muted"></div>
        <div class="h-10 w-48 animate-pulse rounded-md bg-muted"></div>
      </div>
      <div class="mt-2 space-y-3">
        <div class="h-10 w-full animate-pulse rounded bg-muted"></div>
        <div class="h-14 w-full animate-pulse rounded bg-muted"></div>
        <div class="h-14 w-full animate-pulse rounded bg-muted"></div>
        <div class="h-14 w-full animate-pulse rounded bg-muted"></div>
      </div>
    </div>
  {:else if error}
    <div class="flex flex-col items-center justify-center py-20">
      <h2 class="font-bold text-2xl">Virhe</h2>
      <p class="mt-2 text-muted-foreground">{error}</p>
      <a href="/" class="mt-4 text-primary underline">Palaa etusivulle</a>
    </div>
  {:else if competition}
    <div class="flex flex-col gap-4">
      <div class="flex flex-col items-start gap-3">
        <h2
          class="scroll-m-20 border-b pb-2 font-semibold text-2xl tracking-tight first:mt-0 sm:text-3xl"
        >
          {compDetails?.Competition.Name ?? ""}
        </h2>
        <EventSwitcher
          competitionId={compId}
          currentEventId={eventId}
          events={compEvents}
        />
      </div>

      {#key eventId}
        <RoundProvider rounds={competition.Rounds}>
          <div
            class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"
          >
            <RoundSwitcher />
            <ObsPopover slug={`${compId}-${eventId}`} />
          </div>

          <TabsWithHaptics
            defaultValue="participants"
            tabs={[
              {
                value: "participants",
                label: "Ilmoittautuneet",
                icon: usersIcon,
                content: participantsContent,
              },
              {
                value: "protocol",
                label: "Pöytäkirjat",
                icon: clipboardIcon,
                content: protocolContent,
              },
              {
                value: "results",
                label: "Tulokset",
                icon: trophyIcon,
                content: resultsContent,
              },
            ]}
          />
        </RoundProvider>
      {/key}
    </div>
  {/if}
</main>

{#snippet usersIcon()}
  <Users class="size-4" />
{/snippet}

{#snippet clipboardIcon()}
  <ClipboardList class="size-4" />
{/snippet}

{#snippet trophyIcon()}
  <Trophy class="size-4" />
{/snippet}

{#snippet participantsContent()}
  <ParticipantLayout enrollments={competition!.Enrollments} />
{/snippet}

{#snippet protocolContent()}
  <ProtocolLayout {isTrack} />
{/snippet}

{#snippet resultsContent()}
  <ResultProvider
    compId={`${compId}/${eventId}`}
    {isProgress}
    eventCategory={competition!.EventCategory}
  >
    <ResultLayout />
  </ResultProvider>
{/snippet}
