// src/app/(app)/competition/[slug]/page.tsx
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { notFound } from "next/navigation";
import { Suspense } from "react";
import TabsWithHaptics from "~/@/components/tabs-haptics";
import {
  ParticipantLayout,
  ProtocolLayout,
  ResultLayout,
  ResultProvider,
} from "~/@/components/competition-layout";
import { EventSwitcher } from "~/@/components/event-switcher";
import { flattenEvents, type EventWithDate } from "~/@/lib/events";
import { RoundProvider } from "~/@/components/round-provider";
import { RoundSwitcher } from "~/@/components/round-switcher";
import { Skeleton } from "~/@/components/ui/skeleton";

import { api } from "~/trpc/server";
import type { Competition, Events } from "~/types/comp";

const ObsPopover = dynamic(() =>
  import("~/@/components/obs-popover").then((mod) => mod.ObsPopover),
);

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const [compId] = slug.split("-", 2);
  if (!compId) return { title: "Kilpailu - Livetila" };

  try {
    const compDetails = await api.competition.getCompetitionDetails({
      competitionDetailsId: compId,
    });
    return {
      title: `${compDetails.Competition.Name} - Livetila`,
      description: `Seuraa kilpailun ${compDetails.Competition.Name} tuloksia reaaliajassa`,
    };
  } catch {
    return { title: "Kilpailu - Livetila" };
  }
}

/**
 * Async component that fetches athlete data and renders the tab contents.
 * Wrapped in its own Suspense boundary so the page shell streams first.
 */
async function CompetitionContent({
  compId,
  eventId,
  compEvents,
}: {
  compId: string;
  eventId: string;
  compEvents: EventWithDate[];
}) {
  const athletes = await api.competition.getAthletes({
    compId: `${compId}/${eventId}`,
  });

  const selectedEvent = compEvents.find(
    (event) => event.EventId === Number(eventId),
  );

  const isTrack = selectedEvent?.Category === "Track";

  return (
    <RoundProvider key={eventId} rounds={athletes.Rounds}>
      <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <RoundSwitcher />
        <ObsPopover slug={`${compId}-${eventId}`} />
      </div>
      <CompetitionTabs
        athletes={athletes}
        compId={compId}
        eventId={eventId}
        isProgress={selectedEvent?.Status === "Progress"}
        isTrack={isTrack ?? false}
      />
    </RoundProvider>
  );
}

function CompetitionTabs({
  athletes,
  compId,
  eventId,
  isTrack,
  isProgress,
}: {
  athletes: Competition;
  compId: string;
  eventId: string;
  isTrack: boolean;
  isProgress: boolean;
}) {
  return (
    <TabsWithHaptics
      className="mt-2 w-full"
      defaultValue="participants"
      tabs={[
        {
          value: "participants",
          label: "Ilmoittautuneet",
          icon: "users",
          content: (
            <ParticipantLayout enrollments={athletes.Enrollments} />
          ),
        },
        {
          value: "protocol",
          label: "Pöytäkirjat",
          icon: "clipboard-list",
          content: <ProtocolLayout isTrack={isTrack} />,
        },
        {
          value: "results",
          label: "Tulokset",
          icon: "trophy",
          content: (
            <ResultProvider compId={`${compId}/${eventId}`} isProgress={isProgress}>
              <ResultLayout />
            </ResultProvider>
          ),
        },
      ]}
    />
  );
}

export default async function Comp({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const [compId, eventId] = slug.split("-", 2);
  if (!compId || !eventId) {
    notFound();
  }

  const [compEventsRaw, compDetails] = await Promise.all([
    api.competition.getEvents({ compId }),
    api.competition.getCompetitionDetails({ competitionDetailsId: compId }),
  ]);

  const compEvents = flattenEvents(compEventsRaw);

  return (
    <main className="container relative mx-auto flex grow flex-col px-4 py-4 sm:p-8">
      <div className="flex flex-col gap-4">
        <div className="flex flex-col items-start gap-3">
          <h2 className="scroll-m-20 border-b pb-2 font-semibold text-2xl tracking-tight first:mt-0 sm:text-3xl">
            {compDetails ? compDetails.Competition.Name : null}
          </h2>
          <EventSwitcher
            competitionId={compId}
            currentEventId={eventId}
            events={compEvents}
          />
        </div>
        <Suspense
          fallback={
            <div className="flex w-full flex-col gap-2">
              <div className="flex justify-between">
                <Skeleton className="h-8 w-28" />
                <Skeleton className="h-10 w-48" />
              </div>
              <div className="mt-2 space-y-3">
                <Skeleton className="h-10 w-full" />
                <Skeleton className="h-14 w-full" />
                <Skeleton className="h-14 w-full" />
                <Skeleton className="h-14 w-full" />
              </div>
            </div>
          }
        >
          <CompetitionContent
            compEvents={compEvents}
            compId={compId}
            eventId={eventId}
          />
        </Suspense>
      </div>
    </main>
  );
}

// src/routes/(app)/competition/[slug]/+page.svelte
<script lang="ts">
  import { page } from "$app/state";
  import { ClipboardList, Trophy, Users } from "@lucide/svelte";
  import ObsPopover from "$lib/components/obs-popover.svelte";
  import EventSwitcher from "$lib/components/event-switcher.svelte";
  import RoundSwitcher from "$lib/components/round-switcher.svelte";
  import TabsWithHaptics from "$lib/components/tabs-haptics.svelte";
  import RoundProvider from "$lib/components/round-provider.svelte";
  import ResultProvider from "$lib/components/result-provider.svelte";
  import ParticipantLayout from "$lib/components/participant-layout.svelte";
  import ProtocolLayout from "$lib/components/protocol-layout.svelte";
  import ResultLayout from "$lib/components/result-layout.svelte";
  import { flattenEvents } from "$lib/events";
  import { api } from "$lib/api";
  import { createQuery } from "@tanstack/svelte-query";
  import type {
    Competition,
    CompetitionProperties,
    Events,
  } from "~/types/comp";

  const slug = $derived(page.params.slug ?? "");
  const compId = $derived(slug.split("-", 2)[0] ?? "");
  const eventId = $derived(slug.split("-", 2)[1] ?? "");

  const eventsQuery = createQuery<Events>(() => ({
    queryKey: ["events", compId],
    queryFn: () => api.getEvents(compId),
    enabled: Boolean(compId),
  }));

  const compEventsRaw = $derived(eventsQuery.data ?? null);
  const compEvents = $derived(
    compEventsRaw ? flattenEvents(compEventsRaw) : [],
  );
  const selectedEvent = $derived(
    compEvents.find((e) => e.EventId === Number(eventId)),
  );
  const isTrack = $derived(selectedEvent?.Category === "Track");
  const isProgress = $derived(selectedEvent?.Status === "Progress");

  const athletesQuery = createQuery<Competition>(() => ({
    queryKey: ["athletes", compId, eventId],
    queryFn: () => api.getAthletes(`${compId}/${eventId}`),
    enabled: Boolean(compId && eventId),
    refetchInterval: isProgress ? 1000 : false,
    refetchIntervalInBackground: false,
  }));

  const detailsQuery = createQuery<CompetitionProperties>(() => ({
    queryKey: ["competition-details", compId],
    queryFn: () => api.getCompetitionDetails(compId),
    enabled: Boolean(compId),
  }));

  const competition = $derived(athletesQuery.data ?? null);
  const compDetails = $derived(detailsQuery.data ?? null);
  const isLoading = $derived(
    athletesQuery.isPending || detailsQuery.isPending || eventsQuery.isPending,
  );
  const error = $derived(
    athletesQuery.isError ? "Failed to load competition data" : null,
  );
</script>

<svelte:head>
  <title>{compDetails?.Competition.Name ?? "Kilpailu"} - Livetila</title>
</svelte:head>

<main class="container relative mx-auto flex grow flex-col px-4 py-4 sm:p-8">
  {#if !compId || !eventId}
    <div class="flex flex-col items-center justify-center py-20">
      <h2 class="font-bold text-2xl">Virheellinen linkki</h2>
      <a href="/" class="mt-4 text-primary underline">Palaa etusivulle</a>
    </div>
  {:else if isLoading}
    <div class="flex flex-col gap-4">
      <div class="flex items-center justify-between">
        <div class="h-8 w-28 animate-pulse rounded-md bg-muted"></div>
        <div class="h-10 w-48 animate-pulse rounded-md bg-muted"></div>
      </div>
      <div class="mt-2 space-y-3">
        <div class="h-10 w-full animate-pulse rounded bg-muted"></div>
        <div class="h-14 w-full animate-pulse rounded bg-muted"></div>
        <div class="h-14 w-full animate-pulse rounded bg-muted"></div>
        <div class="h-14 w-full animate-pulse rounded bg-muted"></div>
      </div>
    </div>
  {:else if error}
    <div class="flex flex-col items-center justify-center py-20">
      <h2 class="font-bold text-2xl">Virhe</h2>
      <p class="mt-2 text-muted-foreground">{error}</p>
      <a href="/" class="mt-4 text-primary underline">Palaa etusivulle</a>
    </div>
  {:else if competition}
    <div class="flex flex-col gap-4">
      <div class="flex flex-col items-start gap-3">
        <h2
          class="scroll-m-20 border-b pb-2 font-semibold text-2xl tracking-tight first:mt-0 sm:text-3xl"
        >
          {compDetails?.Competition.Name ?? ""}
        </h2>
        <EventSwitcher
          competitionId={compId}
          currentEventId={eventId}
          events={compEvents}
        />
      </div>

      {#key eventId}
        <RoundProvider rounds={competition.Rounds}>
          <div
            class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"
          >
            <RoundSwitcher />
            <ObsPopover slug={`${compId}-${eventId}`} />
          </div>

          <TabsWithHaptics
            defaultValue="participants"
            tabs={[
              {
                value: "participants",
                label: "Ilmoittautuneet",
                icon: usersIcon,
                content: participantsContent,
              },
              {
                value: "protocol",
                label: "Pöytäkirjat",
                icon: clipboardIcon,
                content: protocolContent,
              },
              {
                value: "results",
                label: "Tulokset",
                icon: trophyIcon,
                content: resultsContent,
              },
            ]}
          />
        </RoundProvider>
      {/key}
    </div>
  {/if}
</main>

{#snippet usersIcon()}
  <Users class="size-4" />
{/snippet}

{#snippet clipboardIcon()}
  <ClipboardList class="size-4" />
{/snippet}

{#snippet trophyIcon()}
  <Trophy class="size-4" />
{/snippet}

{#snippet participantsContent()}
  <ParticipantLayout enrollments={competition!.Enrollments} />
{/snippet}

{#snippet protocolContent()}
  <ProtocolLayout {isTrack} />
{/snippet}

{#snippet resultsContent()}
  <ResultProvider
    compId={`${compId}/${eventId}`}
    {isProgress}
    eventCategory={competition!.EventCategory}
  >
    <ResultLayout />
  </ResultProvider>
{/snippet}
