// src/@/components/event-switcher.tsx
"use client";

import { Calendar, Clock } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import { useHaptics } from "~/@/hooks/use-haptics";
import { Badge } from "~/@/components/ui/badge";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "~/@/components/ui/select";
import { flattenEvents, type EventWithDate } from "~/@/lib/events";

const roundMapping = {
	Qualify: "Alkuerät",
	Final: "Loppukilpailu",
} as const;
type RoundKey = keyof typeof roundMapping;
type RoundValue = (typeof roundMapping)[RoundKey];

const statusVariants: Record<
	EventList["Status"],
	"unallocated" | "allocated" | "progress" | "official" | "default"
> = {
	Unallocated: "unallocated",
	Allocated: "allocated",
	Progress: "progress",
	Official: "official",
};

const eventStatusLabel: Record<EventList["Status"], string> = {
	Unallocated: "Eräjaot puuttuvat",
	Allocated: "Eräjaot tehty",
	Progress: "Käynnissä",
	Official: "Tulokset valmiit",
};

const eventNameToRoundCase = (name: string): RoundKey | undefined =>
	Object.entries(roundMapping).find(([, v]) => v === name)?.[0] as
		| RoundKey
		| undefined;

const roundParamToEventName = (round: string | null): RoundValue | null =>
	round && round in roundMapping ? roundMapping[round as RoundKey] : null;

function hasMultipleRoundsForEvent(
	events: EventWithDate[],
	eventName: string,
): boolean {
	const rounds = new Set<string>();
	for (const event of events) {
		if (event.EventName === eventName) {
			const round = eventNameToRoundCase(event.Name);
			if (round) {
				rounds.add(round);
				if (rounds.size > 1) return true; // Early exit
			}
		}
	}
	return false;
}

// Cache the formatter to avoid creating a new instance on every call
const timeFormatter = new Intl.DateTimeFormat("fi-FI", {
	hour: "2-digit",
	minute: "2-digit",
});

function formatTime(date: string): string {
	return timeFormatter.format(new Date(date));
}

function EventDisplay({ event }: { event: EventWithDate }) {
	const time = formatTime(event.BeginDateTimeWithTZ);
	return (
		<div className="flex w-full items-center justify-between gap-2">
			<div className="flex flex-col gap-2">
				<span>
					{event.EventName} {event.Name}
				</span>
				<Badge variant={statusVariants[event.Status] ?? "default"}>
					{eventStatusLabel[event.Status]}
				</Badge>
			</div>

			<div className="flex min-w-[90px] flex-col items-end gap-2 text-muted-foreground text-xs">
				<span className="flex items-center gap-1" suppressHydrationWarning>
					{time}
					<Clock className="size-3" />
				</span>
				<span className="flex items-center gap-1">
					{event.date}
					<Calendar className="size-3" />
				</span>
			</div>
		</div>
	);
}

export function EventSwitcher({
	competitionId,
	events,
	currentEventId,
}: {
	competitionId: string;
	events: EventWithDate[];
	currentEventId: string;
}) {
	const router = useRouter();
	const searchParams = useSearchParams();
	const { feedback } = useHaptics();
	const flattenedEvents = events;
	const roundParam = searchParams.get("round");
	const roundName = roundParamToEventName(roundParam);
	const currentEvent = flattenedEvents.find(
		(e) =>
			e.EventId === Number(currentEventId) &&
			(!roundName || e.Name === roundName),
	);
	function handleEventSelection(value: EventWithDate | null) {
		if (!value) return;
		feedback("selection");
		const params = new URLSearchParams(searchParams.toString());
		const roundCase = eventNameToRoundCase(value.Name);
		const hasMultipleRounds = hasMultipleRoundsForEvent(
			flattenedEvents,
			value.EventName,
		);

		if (hasMultipleRounds && roundCase) {
			params.set("round", roundCase);
		} else {
			params.delete("round");
		}
		router.push(
			`/competition/${competitionId}-${value.EventId}?${params.toString()}`,
		);
	}

	return (
		<Select
			onValueChange={handleEventSelection}
			value={currentEvent?.EventId ? currentEvent : undefined}
		>
			<SelectTrigger className="!h-auto !items-center !py-2 !px-4 w-full focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 sm:w-[400px]">
				<SelectValue className="w-full">
					{(event: EventWithDate) => <EventDisplay event={event} />}
				</SelectValue>
			</SelectTrigger>

			<SelectContent>
				{flattenedEvents.map((event) => (
					<SelectItem
						key={`${event.BeginDateTimeWithTZ}-${event.EventId}-${event.Name}`}
						value={event}
					>
						<EventDisplay event={event} />
					</SelectItem>
				))}
			</SelectContent>
		</Select>
	);
}

// src/lib/components/event-switcher.svelte
<script lang="ts">
  import { Calendar, Clock } from "@lucide/svelte";
  import { goto } from "$app/navigation";
  import { page } from "$app/stores";
  import { triggerHaptic } from "$lib/hooks/use-haptics";
  import Badge from "$lib/components/ui/badge/badge.svelte";
  import type { EventWithDate } from "$lib/events";

  let {
    competitionId,
    events = [],
    currentEventId,
  }: {
    competitionId: string;
    events: EventWithDate[];
    currentEventId: string;
  } = $props();

  const roundMapping = {
    Qualify: "Alkuerät",
    Final: "Loppukilpailu",
  } as const;

  type RoundKey = keyof typeof roundMapping;

  const statusVariants: Record<string, string> = {
    Unallocated: "unallocated",
    Allocated: "allocated",
    Progress: "progress",
    Official: "official",
  };

  const eventStatusLabel: Record<string, string> = {
    Unallocated: "Eräjaot puuttuvat",
    Allocated: "Eräjaot tehty",
    Progress: "Käynnissä",
    Official: "Tulokset valmiit",
  };

  let isOpen = $state(false);

  function eventNameToRoundCase(name: string): RoundKey | undefined {
    return (Object.entries(roundMapping) as [string, string][]).find(
      ([, v]) => v === name,
    )?.[0] as RoundKey | undefined;
  }

  function hasMultipleRoundsForEvent(eventName: string): boolean {
    const rounds = new Set<string>();
    for (const event of events) {
      if (event.EventName === eventName) {
        const round = eventNameToRoundCase(event.Name);
        if (round) {
          rounds.add(round);
          if (rounds.size > 1) return true;
        }
      }
    }
    return false;
  }

  const timeFormatter = new Intl.DateTimeFormat("fi-FI", {
    hour: "2-digit",
    minute: "2-digit",
  });

  function formatTime(date: string): string {
    return timeFormatter.format(new Date(date));
  }

  const currentEvent = $derived(
    events.find((e) => e.EventId === Number(currentEventId)),
  );

  function handleSelect(value: string) {
    triggerHaptic("selection");
    const event = events[Number(value)];
    if (!event) return;
    const roundCase = eventNameToRoundCase(event.Name);
    const hasMultiple = hasMultipleRoundsForEvent(event.EventName);

    let url = `/competition/${competitionId}-${event.EventId}`;
    if (hasMultiple && roundCase) {
      url += `?round=${roundCase}`;
    }
    goto(url);
    isOpen = false;
  }

  function handleOverlayKeydown(event: KeyboardEvent) {
    if (event.key === "Escape") {
      event.preventDefault();
      isOpen = false;
    }
  }
</script>

<div class="relative">
  <button
    class="flex w-full items-center rounded-md border border-input bg-background px-4 py-2 text-sm hover:bg-accent hover:text-accent-foreground focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 sm:w-[400px]"
    onclick={() => (isOpen = !isOpen)}
  >
    {#if currentEvent}
      <div class="flex w-full items-center justify-between gap-2">
        <div class="flex flex-col gap-2">
          <span>{currentEvent.EventName} {currentEvent.Name}</span>
          <Badge variant={statusVariants[currentEvent.Status] || "default"}>
            {eventStatusLabel[currentEvent.Status] || currentEvent.Status}
          </Badge>
        </div>
        <div
          class="flex min-w-[90px] flex-col items-end gap-2 text-muted-foreground text-xs"
        >
          <span class="flex items-center gap-1"
            >{formatTime(currentEvent.BeginDateTimeWithTZ)}
            <Clock class="size-3" /></span
          >
          <span class="flex items-center gap-1"
            >{currentEvent.date} <Calendar class="size-3" /></span
          >
        </div>
      </div>
    {/if}
  </button>

  {#if isOpen}
    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div
      class="fixed inset-0 z-40"
      role="button"
      tabindex="-1"
      aria-label="Sulje valikko"
      onclick={() => (isOpen = false)}
      onkeydown={handleOverlayKeydown}
    ></div>

    <div
      class="absolute left-0 right-0 z-50 mt-1 max-h-96 min-w-[8rem] overflow-auto rounded-md border bg-popover text-popover-foreground shadow-md sm:w-[400px]"
      role="listbox"
    >
      {#each events as event, i}
        <button
          class="flex w-full cursor-pointer items-center rounded-sm px-2 py-1.5 text-sm hover:bg-accent hover:text-accent-foreground {event.EventId ===
          Number(currentEventId)
            ? 'bg-accent'
            : ''}"
          onclick={() => handleSelect(i.toString())}
        >
          <div class="flex w-full items-center justify-between gap-2">
            <div class="flex flex-col gap-1">
              <span>{event.EventName} {event.Name}</span>
              <Badge variant={statusVariants[event.Status] || "default"}>
                {eventStatusLabel[event.Status] || event.Status}
              </Badge>
            </div>
            <div
              class="flex min-w-[90px] flex-col items-end gap-1 text-muted-foreground text-xs"
            >
              <span class="flex items-center gap-1"
                >{formatTime(event.BeginDateTimeWithTZ)}
                <Clock class="size-3" /></span
              >
              <span class="flex items-center gap-1"
                >{event.date} <Calendar class="size-3" /></span
              >
            </div>
          </div>
        </button>
      {/each}
    </div>
  {/if}
</div>
