// src/@/components/search-form.tsx
"use client";

import {
	ArrowRight,
	Calendar,
	ChevronRight,
	Clock,
	Loader2,
	Search,
	Sparkles,
} from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { useRouter } from "next/navigation";
import { useRef, useState } from "react";
import { useHaptics } from "~/@/hooks/use-haptics";
import {
	Command,
	CommandEmpty,
	CommandGroup,
	CommandItem,
	CommandList,
} from "~/@/components/ui/command";
import { api } from "~/trpc/react";
import type { CompetitionList, Events } from "~/types/comp";

type EventData = {
	Id: number;
	EventName: string;
	Name: string;
	Date: string;
	Time: string;
};

function extractEvents(data: Events): EventData[] {
	const results: EventData[] = [];
	for (const dateKey of Object.keys(data)) {
		data[dateKey]?.forEach((event) => {
			const compDate = new Date(event.BeginDateTimeWithTZ);
			const month = String(compDate.getMonth() + 1).padStart(2, "0");
			const day = String(compDate.getDate()).padStart(2, "0");
			const hours = String(compDate.getHours()).padStart(2, "0");
			const minutes = String(compDate.getMinutes()).padStart(2, "0");
			results.push({
				Id: event.EventId,
				EventName: event.EventName,
				Name: event.Name,
				Date: `${day}.${month}.`,
				Time: `${hours}:${minutes}`,
			});
		});
	}
	return results;
}

const smoothSpring = {
	type: "spring" as const,
	stiffness: 300,
	damping: 30,
	mass: 0.8,
};

const staggerChildren = {
	animate: {
		transition: {
			staggerChildren: 0.035,
		},
	},
};

const itemVariants = {
	initial: { opacity: 0, y: 8, scale: 0.96 },
	animate: { opacity: 1, y: 0, scale: 1 },
	exit: { opacity: 0, y: -4, scale: 0.98 },
};

export function SearchForm() {
	const router = useRouter();
	const { feedback } = useHaptics();
	const [query, setQuery] = useState("");
	const [selectedComp, setSelectedComp] = useState<CompetitionList | null>(
		null,
	);
	const [isOpen, setIsOpen] = useState(false);
	const [isFocused, setIsFocused] = useState(false);
	const blurTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
	const inputRef = useRef<HTMLInputElement>(null);

	const { data: competitions, isLoading: isLoadingComps } =
		api.competition.getCompetitions.useQuery();
	const { data: events, isLoading: isLoadingEvents } =
		api.competition.getEvents.useQuery(
			{ compId: selectedComp?.Id.toString() ?? "" },
			{ enabled: !!selectedComp },
		);

	const competitionResults =
		selectedComp || !query.trim()
			? competitions?.sort((a, b) => b.Date.localeCompare(a.Date))
			: competitions?.filter((comp) =>
				comp.Name.toLowerCase().includes(query.toLowerCase()),
			);

	const eventQuery =
		selectedComp && query.includes("/")
			? (query.split("/").pop()?.trim() ?? "")
			: "";

	const eventResults =
		selectedComp && events
			? extractEvents(events)
				.filter(
					(evt) =>
						!eventQuery ||
						evt.EventName.toLowerCase().includes(eventQuery.toLowerCase()),
				)
				.sort((a, b) => a.Time.localeCompare(b.Time))
			: [];

	function handleInputChange(value: string) {
		setIsOpen(true);
		setQuery(value);
		if (selectedComp && !value.includes("/")) {
			setSelectedComp(null);
			setQuery("");
		}
	}

	function handleCompetitionSelect(comp: CompetitionList) {
		feedback("selection");
		setSelectedComp(comp);
		setQuery(`${comp.Name} / `);
		inputRef.current?.focus();
	}

	function handleEventSelect(event: EventData) {
		if (selectedComp) {
			feedback("success");
			router.push(`/competition/${selectedComp.Id}-${event.Id}`);
		}
	}

	function handleBlur() {
		blurTimeoutRef.current = setTimeout(() => {
			setIsOpen(false);
			setIsFocused(false);
		}, 150);
	}

	function handleFocus() {
		if (blurTimeoutRef.current) {
			clearTimeout(blurTimeoutRef.current);
		}
		setIsOpen(true);
		setIsFocused(true);
	}

	const showCompetitions =
		!selectedComp && (competitionResults?.length ?? 0) > 0;
	const showEvents =
		selectedComp && eventResults.length > 0 && !isLoadingEvents;
	const showLoading = isLoadingComps || isLoadingEvents;
	const showEmpty =
		isOpen &&
		query.length > 0 &&
		!showCompetitions &&
		!showEvents &&
		!showLoading;
	const showDropdown =
		isOpen && (showCompetitions || showEvents || showLoading || showEmpty);

	return (
		<div className="relative mx-auto w-full max-w-2xl">
			<Command
				className="overflow-visible bg-transparent"
				role="search"
				shouldFilter={false}
			>
				<motion.div
					animate={{
						scale: isFocused ? 1.01 : 1,
						boxShadow: showDropdown
							? "0 25px 50px -12px rgba(0, 0, 0, 0.25), 0 0 0 1px rgba(255, 255, 255, 0.05)"
							: isFocused
								? "0 10px 25px -5px rgba(0, 0, 0, 0.15), 0 0 0 1px rgba(255, 255, 255, 0.05)"
								: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
					}}
					className="relative overflow-hidden rounded-2xl border border-border/50 bg-card/80 backdrop-blur-xl"
					transition={smoothSpring}
				>
					{/* Gradient border effect */}
					<motion.div
						animate={{
							opacity: isFocused ? 1 : 0,
						}}
						className="pointer-events-none absolute inset-0 rounded-2xl"
						style={{
							background:
								"linear-gradient(135deg, rgba(113, 180, 255, 0.15) 0%, rgba(113, 180, 255, 0.05) 50%, rgba(113, 180, 255, 0.15) 100%)",
						}}
						transition={{ duration: 0.3 }}
					/>

					{/* Input Section */}
					<div className="relative z-10">
						<div className="flex items-center gap-3 px-4 py-3.5">
							<motion.div
								animate={{
									scale: isFocused ? 1.1 : 1,
									color: isFocused
										? "var(--color-primary)"
										: "var(--color-muted-foreground)",
								}}
								transition={smoothSpring}
							>
								<Search className="size-5" />
							</motion.div>

							<div className="relative flex-1">
								<input
									ref={inputRef}
									className="w-full bg-transparent text-base text-foreground placeholder:text-muted-foreground/70 focus:outline-none"
									onBlur={handleBlur}
									onChange={(e) => handleInputChange(e.target.value)}
									onFocus={handleFocus}
									placeholder={
										selectedComp
											? `Hae lajeja...`
											: "Hae kilpailuja nimellä..."
									}
									type="text"
									value={query}
								/>

								{/* Selected competition badge */}
								<AnimatePresence>
									{selectedComp && (
										<motion.div
											animate={{ opacity: 1, x: 0 }}
											className="absolute top-1/2 right-0 -translate-y-1/2"
											exit={{ opacity: 0, x: 10 }}
											initial={{ opacity: 0, x: -10 }}
											transition={smoothSpring}
										>
											<span className="inline-flex items-center gap-1.5 rounded-full bg-primary/15 px-2.5 py-1 font-medium text-primary text-xs">
												<Sparkles className="size-3" />
												{selectedComp.Name.slice(0, 20)}
												{selectedComp.Name.length > 20 ? "..." : ""}
											</span>
										</motion.div>
									)}
								</AnimatePresence>
							</div>

							{/* Loading indicator */}
							<AnimatePresence>
								{showLoading && (
									<motion.div
										animate={{ opacity: 1, scale: 1, rotate: 0 }}
										exit={{ opacity: 0, scale: 0.8 }}
										initial={{ opacity: 0, scale: 0.8 }}
									>
										<Loader2 className="size-5 animate-spin text-primary" />
									</motion.div>
								)}
							</AnimatePresence>
						</div>
					</div>

					{/* Divider */}
					<AnimatePresence>
						{showDropdown && (
							<motion.div
								animate={{ scaleX: 1, opacity: 1 }}
								className="mx-4 h-px bg-linear-to-r from-transparent via-border to-transparent"
								exit={{ scaleX: 0, opacity: 0 }}
								initial={{ scaleX: 0, opacity: 0 }}
								transition={{ duration: 0.2 }}
							/>
						)}
					</AnimatePresence>

					{/* Dropdown */}
					<AnimatePresence mode="wait">
						{showDropdown && (
							<motion.div
								animate={{ height: "auto", opacity: 1 }}
								className="overflow-hidden"
								exit={{ height: 0, opacity: 0 }}
								initial={{ height: 0, opacity: 0 }}
								key={selectedComp ? "events-list" : "competitions-list"}
								transition={{ duration: 0.2, ease: "easeOut" }}
							>
								<div className="p-2">
									<CommandList className="max-h-80 overflow-y-auto">
										{showEmpty && (
											<motion.div
												animate={{ opacity: 1, y: 0 }}
												initial={{ opacity: 0, y: 10 }}
											>
												<CommandEmpty className="flex flex-col items-center gap-2 py-8 text-center">
													<div className="rounded-full bg-muted p-3">
														<Search className="size-5 text-muted-foreground" />
													</div>
													<p className="text-muted-foreground text-sm">
														{selectedComp
															? "Ei lajeja löytynyt"
															: "Ei kilpailuja löytynyt"}
													</p>
												</CommandEmpty>
											</motion.div>
										)}

										{showCompetitions && (
											<CommandGroup
												className="**:[[cmdk-group-heading]]:px-2 **:[[cmdk-group-heading]]:pb-2 **:[[cmdk-group-heading]]:font-semibold **:[[cmdk-group-heading]]:text-muted-foreground/70 **:[[cmdk-group-heading]]:text-xs **:[[cmdk-group-heading]]:uppercase **:[[cmdk-group-heading]]:tracking-wider"
												heading="Kilpailut"
											>
												<motion.div
													animate="animate"
													initial="initial"
													variants={staggerChildren}
												>
													{competitionResults?.slice(0, 10).map((comp) => (
														<motion.div
															key={comp.Id}
															variants={itemVariants}
															transition={smoothSpring}
														>
															<CommandItem
																className="group cursor-pointer rounded-xl px-3 py-2.5 transition-colors data-[selected=true]:bg-primary/10"
																onMouseDown={(event) => event.preventDefault()}
																onSelect={() => handleCompetitionSelect(comp)}
																value={`${comp.Name}-${comp.Date}-${comp.Id}`}
															>
																<div className="flex flex-1 items-center justify-between gap-3">
																	<div className="flex items-center gap-3">
																		<div className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary transition-colors group-data-[selected=true]:bg-primary group-data-[selected=true]:text-primary-foreground">
																			<Calendar className="size-4" />
																		</div>
																		<div className="flex flex-col">
																			<span className="font-medium text-foreground">
																				{comp.Name}
																			</span>
																			<span className="text-muted-foreground text-xs">
																				{new Date(comp.Date).toLocaleDateString(
																					"fi-FI",
																					{
																						day: "numeric",
																						month: "long",
																						year: "numeric",
																					},
																				)}
																			</span>
																		</div>
																	</div>
																	<ArrowRight className="size-4 text-muted-foreground opacity-0 transition-all duration-200 group-data-[selected=true]:translate-x-0.5 group-data-[selected=true]:text-primary group-data-[selected=true]:opacity-100" />
																</div>
															</CommandItem>
														</motion.div>
													))}
												</motion.div>
											</CommandGroup>
										)}

										{isLoadingEvents && (
											<motion.div
												animate={{ opacity: 1 }}
												className="flex flex-col items-center gap-3 py-8"
												initial={{ opacity: 0 }}
											>
												<div className="relative">
													<div className="absolute inset-0 animate-ping rounded-full bg-primary/20" />
													<Loader2 className="relative size-6 animate-spin text-primary" />
												</div>
												<p className="text-muted-foreground text-sm">
													Ladataan lajeja...
												</p>
											</motion.div>
										)}

										{showEvents && (
											<CommandGroup
												className="**:[[cmdk-group-heading]]:px-2 **:[[cmdk-group-heading]]:pb-2 **:[[cmdk-group-heading]]:font-semibold **:[[cmdk-group-heading]]:text-muted-foreground/70 **:[[cmdk-group-heading]]:text-xs **:[[cmdk-group-heading]]:uppercase **:[[cmdk-group-heading]]:tracking-wider"
												heading="Lajit"
											>
												<motion.div
													animate="animate"
													initial="initial"
													variants={staggerChildren}
												>
													{eventResults.slice(0, 15).map((evt) => (
														<motion.div
															key={`${evt.Id}-${evt.Date}-${evt.Time}`}
															variants={itemVariants}
															transition={smoothSpring}
														>
															<CommandItem
																className="group cursor-pointer rounded-xl px-3 py-2.5 transition-colors data-[selected=true]:bg-primary/10"
																onMouseDown={(event) => {
																	event.preventDefault();
																	handleEventSelect(evt);
																}}
																onSelect={() => handleEventSelect(evt)}
																value={`${evt.EventName}-${evt.Date}-${evt.Time}-${evt.Id}`}
															>
																<div className="flex w-full items-center justify-between gap-3">
																	<div className="flex items-center gap-3">
																		<div className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-accent text-accent-foreground transition-colors group-data-[selected=true]:bg-primary group-data-[selected=true]:text-primary-foreground">
																			<Clock className="size-4" />
																		</div>
																		<div className="flex flex-col">
																			<span className="font-medium text-foreground">
																				{evt.EventName}
																			</span>
																			<span className="text-muted-foreground text-xs">
																				{evt.Name}
																			</span>
																		</div>
																	</div>
																	<div className="flex items-center gap-3">
																		<div className="flex items-center gap-2 text-muted-foreground text-xs">
																			<span className="rounded-md bg-muted px-2 py-0.5 font-mono">
																				{evt.Time}
																			</span>
																			<span>{evt.Date}</span>
																		</div>
																		<ChevronRight className="size-4 text-muted-foreground opacity-0 transition-all duration-200 group-data-[selected=true]:translate-x-0.5 group-data-[selected=true]:text-primary group-data-[selected=true]:opacity-100" />
																	</div>
																</div>
															</CommandItem>
														</motion.div>
													))}
												</motion.div>
											</CommandGroup>
										)}
									</CommandList>
								</div>
							</motion.div>
						)}
					</AnimatePresence>
				</motion.div>
			</Command>

			{/* Hint text */}
			<AnimatePresence>
				{!showDropdown && (
					<motion.p
						animate={{ opacity: 1, y: 0 }}
						className="mt-3 text-center text-muted-foreground/60 text-xs"
						exit={{ opacity: 0, y: -5 }}
						initial={{ opacity: 0, y: 5 }}
						transition={{ delay: 0.1 }}
					>
						Vinkki: valitse kilpailu ja rajaa laji kirjoittamalla {`"/"`}
					</motion.p>
				)}
			</AnimatePresence>
		</div>
	);
}

// src/lib/components/search-form.svelte
<script lang="ts">
  import { fly, fade, slide, scale } from "svelte/transition";
  import { cubicOut, cubicInOut } from "svelte/easing";
  import {
    ArrowRight,
    Calendar,
    ChevronRight,
    Clock,
    LoaderCircle,
    Search,
  } from "@lucide/svelte";
  import { createWebHaptics } from "web-haptics/svelte";
  import { onDestroy } from "svelte";
  import { goto } from "$app/navigation";
  import { api } from "$lib/api";
  import type { CompetitionList, Events } from "~/types/comp";

  import {
    Command,
    CommandEmpty,
    CommandGroup,
    CommandItem,
    CommandList,
  } from "$lib/components/ui/command";
  import { cn } from "$lib/utils.js";

  type EventData = {
    Id: number;
    EventName: string;
    Name: string;
    Date: string;
    Time: string;
  };

  type SearchStep = "competitions" | "events";

  function extractEvents(data: Events): EventData[] {
    const results: EventData[] = [];
    for (const dateKey of Object.keys(data)) {
      const events = data[dateKey];
      if (events) {
        for (const event of events) {
          const compDate = new Date(event.BeginDateTimeWithTZ);
          results.push({
            Id: event.EventId,
            EventName: event.EventName,
            Name: event.Name,
            Date: `${String(compDate.getDate()).padStart(2, "0")}.${String(compDate.getMonth() + 1).padStart(2, "0")}.`,
            Time: `${String(compDate.getHours()).padStart(2, "0")}:${String(compDate.getMinutes()).padStart(2, "0")}`,
          });
        }
      }
    }
    return results;
  }

  const groupHeadingClassName =
    "**:[[cmdk-group-heading]]:px-2 **:[[cmdk-group-heading]]:pb-2 **:[[cmdk-group-heading]]:font-semibold **:[[cmdk-group-heading]]:text-muted-foreground/70 **:[[cmdk-group-heading]]:text-xs **:[[cmdk-group-heading]]:uppercase **:[[cmdk-group-heading]]:tracking-wider";

  let query = $state("");
  let isOpen = $state(false);
  let isFocused = $state(false);
  let selectedComp = $state<CompetitionList | null>(null);
  let navigatingTo = $state<number | null>(null);

  let inputEl: HTMLInputElement | undefined = $state(undefined);
  let blurTimeout: ReturnType<typeof setTimeout> | undefined =
    $state(undefined);

  let competitions = $state.raw<CompetitionList[]>([]);
  let events = $state.raw<Events>({});
  let isLoadingComps = $state.raw(true);
  let isLoadingEvents = $state.raw(false);

  $effect(() => {
    api
      .getCompetitions()
      .then((data) => {
        competitions = data;
        isLoadingComps = false;
      })
      .catch(() => {
        isLoadingComps = false;
      });
  });

  $effect(() => {
    if (selectedComp) {
      isLoadingEvents = true;
      api
        .getEvents(selectedComp.Id.toString())
        .then((data) => {
          events = data;
          isLoadingEvents = false;
        })
        .catch(() => {
          isLoadingEvents = false;
        });
    }
  });

  const step = $derived<SearchStep>(selectedComp ? "events" : "competitions");

  const filteredCompetitions = $derived.by<CompetitionList[]>(() => {
    if (!competitions.length) return [];
    const sorted = [...competitions].sort((a, b) =>
      b.Date.localeCompare(a.Date),
    );
    if (!query.trim()) return sorted;
    return sorted.filter((comp) =>
      comp.Name.toLowerCase().includes(query.toLowerCase()),
    );
  });

  const filteredEvents = $derived.by<EventData[]>(() => {
    if (!events) return [];
    const allEvents = extractEvents(events).sort((a, b) =>
      a.Time.localeCompare(b.Time),
    );
    const eventQuery = query.includes("/")
      ? (query.split("/").pop()?.trim() ?? "")
      : "";
    if (!eventQuery) return allEvents;
    return allEvents.filter((evt) =>
      evt.EventName.toLowerCase().includes(eventQuery.toLowerCase()),
    );
  });

  const isLoading = $derived(
    step === "competitions" ? isLoadingComps : isLoadingEvents,
  );
  const results = $derived(
    step === "competitions" ? filteredCompetitions : filteredEvents,
  );
  const hasResults = $derived(results.length > 0);
  const showDropdown = $derived(
    isOpen && (isLoading || hasResults || query.length > 0),
  );

  let dropdownKey = $derived.by(() => {
    void step;
    return Date.now();
  });

  function handleInput(value: string) {
    query = value;
    if (!isOpen) isOpen = true;
    if (selectedComp && !value.includes("/")) {
      selectedComp = null;
      query = "";
    }
  }

  const { trigger, destroy } = createWebHaptics();
  onDestroy(destroy);

  function handleCompetitionSelect(comp: CompetitionList) {
    trigger();
    selectedComp = comp;
    query = `${comp.Name} / `;
    inputEl?.focus();
  }

  function handleEventSelect(evt: EventData) {
    if (!selectedComp || navigatingTo !== null) return;
    trigger();
    navigatingTo = evt.Id;
    goto(`/competition/${selectedComp.Id}-${evt.Id}`);
  }

  function handleFocus() {
    if (blurTimeout) clearTimeout(blurTimeout);
    isOpen = true;
    isFocused = true;
  }

  function handleBlur() {
    blurTimeout = setTimeout(() => {
      isOpen = false;
      isFocused = false;
    }, 150);
  }
</script>

<div class="relative mx-auto w-full max-w-2xl">
  <Command
    class="overflow-visible bg-transparent"
    role="search"
    shouldFilter={false}
  >
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div
      class={cn(
        "relative overflow-hidden rounded-2xl border border-border/50 bg-card/80 backdrop-blur-xl transition-all duration-300 ease-out",
        isFocused && "focused",
      )}
      style="box-shadow: {showDropdown
        ? '0 25px 50px -12px rgba(0, 0, 0, 0.25), 0 0 0 1px rgba(255, 255, 255, 0.05)'
        : isFocused
          ? '0 10px 25px -5px rgba(0, 0, 0, 0.15), 0 0 0 1px rgba(255, 255, 255, 0.05)'
          : '0 4px 6px -1px rgba(0, 0, 0, 0.1)'}"
    >
      <div
        class={cn(
          "pointer-events-none absolute inset-0 rounded-2xl transition-opacity duration-300",
          isFocused ? "opacity-100" : "opacity-0",
        )}
        style="background: linear-gradient(135deg, rgba(113, 180, 255, 0.15) 0%, rgba(113, 180, 255, 0.05) 50%, rgba(113, 180, 255, 0.15) 100%)"
      ></div>

      <div class="relative z-10">
        <div
          class="flex items-center gap-2 px-3 py-3 sm:gap-3 sm:px-4 sm:py-3.5"
        >
          <span
            class={cn(
              "inline-flex transition-all duration-300 ease-out",
              isFocused && "scale-110 text-primary",
              !isFocused && "text-muted-foreground",
            )}
          >
            <Search class="size-5" />
          </span>

          <input
            bind:this={inputEl}
            class="w-full bg-transparent text-sm text-foreground placeholder:text-muted-foreground/70 focus:outline-none sm:text-base"
            onblur={handleBlur}
            oninput={(e) => handleInput((e.target as HTMLInputElement).value)}
            onfocus={handleFocus}
            placeholder={step === "events"
              ? "Hae lajeja..."
              : "Hae kilpailuja nimellä..."}
            type="text"
            value={query}
          />

          {#if isLoading}
            <div
              in:scale={{ duration: 150, start: 0.8 }}
              out:scale={{ duration: 150, start: 0.8 }}
            >
              <LoaderCircle class="size-5 animate-spin text-primary" />
            </div>
          {/if}
        </div>
      </div>

      {#if showDropdown}
        <div
          in:scale={{ duration: 200, start: 0 }}
          out:scale={{ duration: 200, start: 0 }}
          class="mx-4 h-px bg-linear-to-r from-transparent via-border to-transparent"
        ></div>
      {/if}

      {#key dropdownKey}
        {#if showDropdown}
          <div
            in:slide={{ duration: 200, easing: cubicOut }}
            out:slide={{ duration: 200, easing: cubicInOut }}
            class="overflow-hidden"
          >
            <div class="p-2">
              <CommandList class="max-h-80 overflow-y-auto">
                {#if isLoading}
                  <div
                    in:fade={{ duration: 150 }}
                    class="flex flex-col items-center gap-3 py-8"
                  >
                    <div class="relative">
                      <div
                        class="absolute inset-0 animate-ping rounded-full bg-primary/20"
                      ></div>
                      <LoaderCircle
                        class="relative size-6 animate-spin text-primary"
                      />
                    </div>
                    <p class="text-muted-foreground text-sm">
                      {step === "events"
                        ? "Ladataan lajeja..."
                        : "Ladataan kilpailuja..."}
                    </p>
                  </div>
                {:else if !hasResults}
                  <div in:fly={{ y: 10, duration: 200 }}>
                    <CommandEmpty
                      class="flex flex-col items-center gap-2 py-8 text-center"
                    >
                      <div class="rounded-full bg-muted p-3">
                        <Search class="size-5 text-muted-foreground" />
                      </div>
                      <p class="text-muted-foreground text-sm">
                        {step === "events"
                          ? "Ei lajeja löytynyt"
                          : "Ei kilpailuja löytynyt"}
                      </p>
                    </CommandEmpty>
                  </div>
                {:else if step === "competitions" && hasResults}
                  <CommandGroup
                    class={groupHeadingClassName}
                    heading="Kilpailut"
                  >
                    {#each filteredCompetitions.slice(0, 10) as comp, i (comp.Id)}
                      <div
                        in:fly={{ y: 8, duration: 250, delay: i * 35 }}
                        out:fly={{ y: -4, duration: 150 }}
                        class="active-press"
                      >
                        <CommandItem
                          class="group cursor-pointer rounded-xl px-2 py-2 transition-colors data-selected:bg-primary/10 active:bg-primary/15 sm:px-3 sm:py-2.5"
                          onmousedown={(e) => {
                            e.preventDefault();
                          }}
                          onSelect={() => handleCompetitionSelect(comp)}
                          value={`${comp.Name}-${comp.Id}`}
                        >
                          <div
                            class="flex flex-1 items-center justify-between gap-2 sm:gap-3"
                          >
                            <div class="flex items-center gap-2 sm:gap-3">
                              <div
                                class="flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary transition-colors group-data-selected:bg-primary group-data-selected:text-primary-foreground sm:size-9"
                              >
                                <Calendar class="size-4" />
                              </div>
                              <div class="flex flex-col">
                                <span
                                  class="font-medium text-foreground text-sm sm:text-base"
                                  >{comp.Name}</span
                                >
                                <span class="text-muted-foreground text-xs">
                                  {new Date(comp.Date).toLocaleDateString(
                                    "fi-FI",
                                    {
                                      day: "numeric",
                                      month: "long",
                                      year: "numeric",
                                    },
                                  )}
                                </span>
                              </div>
                            </div>
                            <ArrowRight
                              class="size-4 text-muted-foreground opacity-0 transition-all duration-200 group-data-selected:translate-x-0.5 group-data-selected:text-primary group-data-selected:opacity-100"
                            />
                          </div>
                        </CommandItem>
                      </div>
                    {/each}
                  </CommandGroup>
                {:else if step === "events" && hasResults}
                  <CommandGroup class={groupHeadingClassName} heading="Lajit">
                    {#each filteredEvents.slice(0, 15) as evt, i (evt.Id + evt.Time)}
                      {@const isNavigating = navigatingTo === evt.Id}
                      {@const isDisabled =
                        navigatingTo !== null && !isNavigating}
                      <div
                        in:fly={{ y: 8, duration: 250, delay: i * 35 }}
                        out:fly={{ y: -4, duration: 150 }}
                      >
                        <CommandItem
                          class="group cursor-pointer rounded-xl px-2 py-2 transition-all data-selected:bg-primary/10 active:bg-primary/15 disabled:pointer-events-none sm:px-3 sm:py-2.5"
                          disabled={isDisabled}
                          onmousedown={(e) => {
                            e.preventDefault();
                            handleEventSelect(evt);
                          }}
                          onSelect={() => handleEventSelect(evt)}
                          style="opacity: {isDisabled ? 0.4 : 1}"
                          value={`${evt.EventName}-${evt.Id}`}
                        >
                          <div
                            class="flex w-full items-center justify-between gap-2 sm:gap-3"
                          >
                            <div class="flex items-center gap-2 sm:gap-3">
                              <div
                                class="relative flex size-8 shrink-0 items-center justify-center rounded-lg bg-accent text-accent-foreground transition-colors group-data-selected:bg-primary group-data-selected:text-primary-foreground sm:size-9"
                              >
                                {#if isNavigating}
                                  <LoaderCircle class="size-4 animate-spin" />
                                {:else}
                                  <Clock class="size-4" />
                                {/if}
                              </div>
                              <div class="flex flex-col">
                                <span
                                  class="font-medium text-foreground text-sm sm:text-base"
                                  >{evt.EventName}</span
                                >
                                <span
                                  in:fly={{ y: 4, duration: 150, delay: 50 }}
                                  out:fly={{ y: -4, duration: 150 }}
                                  class="text-muted-foreground text-xs"
                                >
                                  {isNavigating ? "Siirrytään..." : evt.Name}
                                </span>
                              </div>
                            </div>
                            <div class="flex items-center gap-2 sm:gap-3">
                              <div
                                class="hidden items-center gap-2 text-muted-foreground text-xs sm:flex"
                              >
                                <span
                                  class="rounded-md bg-muted px-2 py-0.5 font-mono"
                                  >{evt.Time}</span
                                >
                                <span>{evt.Date}</span>
                              </div>
                              <span
                                class="rounded-md bg-muted px-1.5 py-0.5 font-mono text-muted-foreground text-xs sm:hidden"
                                >{evt.Time}</span
                              >
                              {#if isNavigating}
                                <div class="size-4"></div>
                              {:else}
                                <ChevronRight
                                  class="size-4 text-muted-foreground opacity-0 transition-all duration-200 group-data-selected:translate-x-0.5 group-data-selected:text-primary group-data-selected:opacity-100"
                                />
                              {/if}
                            </div>
                          </div>
                        </CommandItem>
                      </div>
                    {/each}
                  </CommandGroup>
                {/if}
              </CommandList>
            </div>
          </div>
        {/if}
      {/key}
    </div>
  </Command>

  {#if !showDropdown}
    <p
      in:fly={{ y: 5, duration: 200, delay: 100 }}
      out:fly={{ y: -5, duration: 150 }}
      class="mt-3 text-center text-muted-foreground/60 text-xs"
    >
      Vinkki: valitse kilpailu ja rajaa laji kirjoittamalla "/"
    </p>
  {/if}
</div>

<style>
  .focused {
    scale: 1.01;
  }
  .active-press:active {
    scale: 0.97;
  }
</style>
