// src/lib/components/round-provider.svelte
<script module lang="ts">
  import { getContext, setContext } from "svelte";
  import type { Heat, Round } from "~/types/comp";

  const ROUND_CONTEXT_KEY = Symbol("round-provider");

  export type RoundContext = {
    rounds: Round[];
    selectedRound: number;
    selectedHeat: number;
    currentRound: Round;
    currentHeat: Heat;
    heats: Heat[];
    showHeatNumbers: boolean;
    handleRoundChange: (index: number) => void;
    handleHeatChange: (index: number) => void;
  };

  export function getRoundContext(): RoundContext {
    return getContext(ROUND_CONTEXT_KEY);
  }
</script>

<script lang="ts">
  import { triggerHaptic } from "$lib/hooks/use-haptics";

  let {
    rounds = [],
    children,
  }: {
    rounds: Round[];
    children: import("svelte").Snippet;
  } = $props();

  let selectedRound = $state(0);
  let selectedHeat = $state(1);

  $effect(() => {
    if (rounds.length > 0 && selectedRound === 0) {
      selectedRound = rounds.at(-1)?.Index ?? 0;
    }
  });

  const currentRound = $derived(
    rounds.find((r) => r.Index === selectedRound) ?? rounds[0],
  );
  const heats = $derived(currentRound?.Heats ?? []);
  const currentHeat = $derived(
    heats.find((h) => h.Index === selectedHeat) ?? heats[0],
  );
  const showHeatNumbers = $derived(heats.length >= 2);

  function handleRoundChange(index: number) {
    triggerHaptic("selection");
    selectedRound = index;
    const round = rounds.find((r) => r.Index === index);
    selectedHeat = round?.Heats?.[0]?.Index ?? 1;
  }

  function handleHeatChange(index: number) {
    if (heats.some((h) => h.Index === index)) {
      triggerHaptic("selection");
      selectedHeat = index;
    }
  }

  setContext(ROUND_CONTEXT_KEY, {
    get rounds() {
      return rounds;
    },
    get selectedRound() {
      return selectedRound;
    },
    get selectedHeat() {
      return selectedHeat;
    },
    get currentRound() {
      return currentRound;
    },
    get currentHeat() {
      return currentHeat;
    },
    get heats() {
      return heats;
    },
    get showHeatNumbers() {
      return showHeatNumbers;
    },
    handleRoundChange,
    handleHeatChange,
  });
</script>

{@render children()}

// src/@/components/round-provider.tsx
"use client";
import { createContext, type ReactNode, useContext } from "react";
import { useEventRounds } from "~/@/hooks/use-event-rounds";
import type { Heat, Round } from "~/types/comp";

interface EventContextType {
	selectedRound: number;
	selectedHeat: number;
	currentRound: Round | undefined;
	currentHeat: Heat | undefined;
	heats: Heat[];
	showHeatNumbers: boolean;
	handleRoundChange: (roundIndex: number) => void;
	handleHeatChange: (heatIndex: number) => void;
}

const RoundContext = createContext<EventContextType | undefined>(undefined);

interface EventProviderProps {
	children: ReactNode;
	rounds: Round[];
}

export function RoundProvider({ children, rounds }: EventProviderProps) {
	const roundsState = useEventRounds(rounds);

	return (
		<RoundContext.Provider value={roundsState}>
			{children}
		</RoundContext.Provider>
	);
}

export function useRound() {
	const context = useContext(RoundContext);
	if (context === undefined) {
		throw new Error("useEvent must be used within an EventProvider");
	}
	return context;
}
