// src/lib/components/round-switcher.svelte
<script lang="ts">
  import { Button } from "$lib/components/ui/button";
  import { getRoundContext } from "./round-provider.svelte";

  const ctx = getRoundContext();
</script>

{#if ctx.rounds.length > 1}
  <div class="flex flex-wrap gap-2">
    {#each ctx.rounds as round (round.Index)}
      <Button
        size="sm"
        variant={ctx.selectedRound === round.Index ? "default" : "outline"}
        onclick={() => ctx.handleRoundChange(round.Index)}
      >
        {round.RoundTypeCategory === "Qualify"
          ? "Alkuerät"
          : round.RoundTypeCategory === "Final"
            ? "Loppukilpailu"
            : round.Name}
      </Button>
    {/each}
  </div>
{/if}

// src/@/components/round-switcher.tsx
"use client";

import { useRound } from "~/@/components/round-provider";
import type { Round } from "~/types/comp";
import { Button } from "~/@/components/ui/button";

function roundLabel(round: Round) {
  switch (round.RoundTypeCategory) {
    case "Qualify":
      return "Alkuerät";
    case "Final":
      return "Loppukilpailu";
    default:
      return round.Name;
  }
}

export function RoundSwitcher() {
  const { rounds, selectedRound, handleRoundChange } = useRound();

  if (rounds.length <= 1) {
    return null;
  }

  return (
    <div className="flex gap-2">
      {rounds.map((round) => (
        <Button
          key={round.Index}
          onClick={() => handleRoundChange(round.Index)}
          variant={selectedRound === round.Index ? "default" : "outline"}
        >
          {roundLabel(round)}
        </Button>
      ))}
    </div>
  );
}
